from basic_app.models.base import *
from basic_app.models.news import *
from basic_app.models.post import *
from basic_app.models.navbar import *
from basic_app.models.workers import *
from basic_app.models.interactive_map import *
from basic_app.models.youtube import *
from basic_app.models.elon import *
from basic_app.models.banner import *
from basic_app.models.tuzilma import *
from basic_app.models.maqsad import *
from basic_app.models.bolimlar import *