# Generated by Django 4.2.7 on 2024-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0002_administrator_admission_days_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="subtitle",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="news",
            name="subtitle_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="news",
            name="subtitle_ru",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="news",
            name="subtitle_uz",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="posts",
            name="subtitle",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="posts",
            name="subtitle_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="posts",
            name="subtitle_ru",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="posts",
            name="subtitle_uz",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
    ]
