# Generated by Django 4.2.7 on 2024-11-28 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0005_youtube"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtube",
            options={
                "managed": True,
                "verbose_name": "YouTube",
                "verbose_name_plural": "YouTube",
            },
        ),
        migrations.AddField(
            model_name="youtube",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
