# Generated by Django 4.2.7 on 2024-11-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("basic_app", "0007_news_created_at_posts_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/%Y-%m-%d/",
                        verbose_name="Asosiy rasm",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Sarlavha"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Short title"
                    ),
                ),
                (
                    "post",
                    django_quill.fields.QuillField(
                        blank=True, null=True, verbose_name="To'liq mazmuni"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pub", "Published"), ("pen", "Pending")],
                        default="pen",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Majburyat tug'ulmasa tegmang",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "post_viewed_count",
                    models.IntegerField(
                        default=0,
                        help_text="Tegilmasin !",
                        verbose_name="Ko'rilganlik soni",
                    ),
                ),
                (
                    "author_post",
                    models.CharField(max_length=300, verbose_name="Muallifi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Faqat *.pdf formatdagi faylarni yuklang",
                        null=True,
                        upload_to="pdf/news/%Y-%m-%d/",
                        verbose_name="PDF fayl",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="agar video fayl mavjud bo'lsa yuklang.",
                        null=True,
                        upload_to="videos/news/%Y-%m-%d/",
                        verbose_name="Video fayl",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Elon",
                "verbose_name_plural": "Elon",
                "db_table": "Elon",
                "managed": True,
            },
        ),
    ]
