# Generated by Django 4.2.7 on 2024-12-04 13:55

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0010_alter_elon_created_at_alter_elon_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="author_post_en",
            field=models.CharField(max_length=300, null=True, verbose_name="Muallifi"),
        ),
        migrations.AddField(
            model_name="banner",
            name="author_post_ru",
            field=models.CharField(max_length=300, null=True, verbose_name="Muallifi"),
        ),
        migrations.AddField(
            model_name="banner",
            name="author_post_uz",
            field=models.CharField(max_length=300, null=True, verbose_name="Muallifi"),
        ),
        migrations.AddField(
            model_name="banner",
            name="post_en",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="To'liq mazmuni"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="post_ru",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="To'liq mazmuni"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="post_uz",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="To'liq mazmuni"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="subtitle_en",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Short title"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="subtitle_ru",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Short title"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="subtitle_uz",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Short title"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_ru",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_uz",
            field=models.CharField(max_length=500, null=True, verbose_name="Sarlavha"),
        ),
    ]
