# Generated by Django 4.2.7 on 2024-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0012_remove_administrator_admission_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="administrator",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="administrator",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
    ]
