# Generated by Django 4.2.7 on 2024-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0015_tuzilma_name_en_tuzilma_name_ru_tuzilma_name_uz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maqsad",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="To'liq ismi"
            ),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="To'liq ismi"
            ),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="To'liq ismi"
            ),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="position_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="position_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="position_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
        migrations.AddField(
            model_name="maqsad",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Lavozimi"),
        ),
    ]
