# Generated by Django 4.2.7 on 2024-12-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "basic_app",
            "0018_bolimlar_name_en_bolimlar_name_ru_bolimlar_name_uz_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bolimlar",
            options={
                "verbose_name": "bolimlarishchi",
                "verbose_name_plural": "bolimlarishchi",
            },
        ),
        migrations.AlterModelTable(
            name="bolimlar",
            table="bolimlarishchi",
        ),
    ]
